# Generated by Django 3.1.2 on 2020-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_post', '0002_auto_20201030_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinesspost',
            name='error_on_upload_image',
            field=models.BooleanField(default=False),
        ),
    ]
