# Generated by Django 3.1.2 on 2020-12-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_post', '0003_bussinesspost_error_on_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinesspost',
            name='error_on_upload_image',
        ),
    ]
