# Generated by Django 3.0.7 on 2020-07-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_country'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
