# Generated by Django 3.0.7 on 2020-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ios2', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('country_code', models.IntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
