# Generated by Django 3.1.2 on 2020-11-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountpost',
            table='account_post',
        ),
        migrations.AlterModelTable(
            name='postimage',
            table='post_image',
        ),
    ]
