# Generated by Django 3.1.2 on 2020-12-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_post', '0002_auto_20201119_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpost',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountpost',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountpost',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
