# Generated by Django 3.1.2 on 2020-12-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_post', '0003_auto_20201221_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpost',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
