# Generated by Django 3.1.2 on 2020-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_post', '0004_auto_20201222_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpost',
            name='error_happened_on_uploading_image',
            field=models.BooleanField(default=False),
        ),
    ]
