# Generated by Django 3.1.2 on 2021-02-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_post', '0010_auto_20210214_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpost',
            name='post_type',
            field=models.IntegerField(choices=[(1, 'normal-post'), (2, 'recommendation')], default=1),
        ),
        migrations.AlterField(
            model_name='accountpost',
            name='recommendation_type',
            field=models.IntegerField(blank=True, choices=[(1, 'business'), (2, 'product'), (3, 'place')], null=True),
        ),
    ]
