# Generated by Django 3.1.2 on 2020-11-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201118_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
        migrations.AlterModelTable(
            name='userlocation',
            table='user_location',
        ),
    ]
