# Generated by Django 3.0.7 on 2020-07-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
