# Generated by Django 3.0.7 on 2020-07-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussinesslocation',
            name='bussiness',
        ),
        migrations.DeleteModel(
            name='Bussiness',
        ),
        migrations.DeleteModel(
            name='BussinessLocation',
        ),
    ]
