# Generated by Django 3.0.7 on 2020-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0002_bussiness_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
