# Generated by Django 3.0.7 on 2020-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0002_bussiness_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='profile_name',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
