# Generated by Django 3.0.7 on 2020-08-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_bussiness_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics_demo'),
        ),
    ]
