# Generated by Django 3.0.7 on 2020-07-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0003_bussiness_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussiness',
            old_name='profile_name',
            new_name='profile_image',
        ),
    ]
