# Generated by Django 3.1.2 on 2020-10-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0004_auto_20200806_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bussiness',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Business'},
        ),
    ]
