# Generated by Django 3.1.2 on 2020-10-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0005_auto_20201030_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='category',
        ),
    ]
