# Generated by Django 3.1.2 on 2020-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0006_remove_bussiness_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_pics_demo')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('lattitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Business',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='bussiness',
            name='country',
        ),
        migrations.RemoveField(
            model_name='bussiness',
            name='user',
        ),
    ]
