# Generated by Django 3.1.2 on 2020-10-30 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_post', '0002_auto_20201030_1243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_data', '0003_auto_20201030_1016'),
        ('bussiness', '0007_auto_20201030_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bussiness',
        ),
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.country'),
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_business', to=settings.AUTH_USER_MODEL),
        ),
    ]
