# Generated by Django 3.1.2 on 2020-10-30 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_auto_20201030_1016'),
        ('bussiness', '0009_auto_20201030_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bussiness_category', to='master_data.hashtag'),
        ),
    ]
