# Generated by Django 3.1.2 on 2020-11-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0011_remove_bussiness_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='lattitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bussiness',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
