# Generated by Django 3.1.2 on 2020-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0012_auto_20201105_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussiness',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
