# Generated by Django 3.1.2 on 2020-11-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness', '0013_auto_20201105_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bussiness',
            name='country',
        ),
    ]
