# Generated by Django 3.1.2 on 2020-11-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bio',
            new_name='account_bio',
        ),
    ]
